### ISSUE TITLE
Console test application fails on run

### ISSUE THREAD

**Issue by SesticM** [bertt/GdalOnNet6Sample#4]
Bert, console test application (https://github.com/bertt/GdalOnNetCoreSample) throws following exception when run: `Unhandled exception. System.EntryPointNotFoundException: Unable to find an entry point named ‘CSharp_OSGeofGDAL_AllRegister___’ in DLL ‘gdal_wrap’.`

**Comment by bertt** [comment]
Hi Maksim, what operating system (windows/mac/linux) do you use?

**Comment by SesticM** [comment]
It's Windows 10 OS, Visual Studio 2019 (latest revision)

**Comment by SesticM** [comment]
Oh, I see what's wrong - I already have `GDAL_DATA` environment setting related to standard GDAL's .NET Framework implementation. It's obviously taken into consideration before `..\netcoreapp3.1\runtimes\win10-x64\native` dependencies being shipped by Nuget. To fix this, I copied all `..\native` files & folders to Console app's Debug folder and now everything works fine. You might want to add this tiny comment to the project's Readme, or improve referenced dlls probing if possible.

**Comment by bertt** [comment]
I've updated the sample, it's now using gdal 3.3.3
